import Vue from 'vue'
// import Vuetify from 'vuetify'
import {
    Vuetify,
    VApp,
    VNavigationDrawer,
    VFooter,
    VList,
    VBtn,
    VIcon,
    VGrid,
    VCard,
    VToolbar,
    VDialog,
    VTextField,
    VSelect,
    VAutocomplete,
    VSpeedDial,
    VTooltip,
    VTabs,
    VAvatar,
    VBottomNav,
    VDivider,
    VChip,
    VDataTable,
    VProgressLinear,
    VBadge,
    VTextarea,
    VAlert,
    VSnackbar,
    VCheckbox,
    VDatePicker,
    VParallax,
    VMenu,
    VStepper,
    VProgressCircular,    
    VImg,
    VHover,
    VSubheader,
    VForm,
    VSlider,
    transitions
} from 'vuetify'
import { Ripple } from 'vuetify/es5/directives'

// import 'vuetify/src/stylus/app.styl'
import {THEME_PRIMS} from '../const'

Vue.use(Vuetify, {
    theme : THEME_PRIMS,
    components: {
        Vuetify,
        VApp,
        VNavigationDrawer,
        VFooter,
        VList,
        VBtn,
        VIcon,
        VGrid,
        VCard,
        VToolbar,
        VDialog,
        VTextField,
        VSelect,
        VSpeedDial,
        VAutocomplete,
        VTooltip,
        VTabs,
        VAvatar,
        VBottomNav,
        VDivider,
        VChip,
        VDataTable,
        VProgressLinear,
        VBadge,
        VTextarea,
        VAlert,
        VSnackbar,
        VCheckbox,
        VDatePicker,
        VParallax,  
        VMenu,  
        VStepper,
        VProgressCircular,  
        VImg,      
        VHover,
        VSubheader,
        VForm,
        VSlider,
        transitions,        
      },
      directives: {
        Ripple
      }    
})